# Generated by Django 5.1.1 on 2024-10-15 03:44

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images/', validators=[Petstagram.photos.validators.validate_photos]),
        ),
    ]
