# Generated by Django 5.1.3 on 2024-11-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_workshop_is_online_alter_workshop_meeting_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(),
        ),
    ]
