# Generated by Django 5.1.3 on 2024-11-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_artoniauser_groups_and_more'),
        ('macrame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrame',
            name='difficulty_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='macrame',
            name='knot_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macrame',
            name='knot_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='macrame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.artoniauser'),
        ),
        migrations.DeleteModel(
            name='KnotType',
        ),
    ]
