# Generated by Django 5.1.3 on 2024-11-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrame', '0002_macrame_difficulty_level_macrame_knot_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrame',
            name='bidder',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macrame',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='macrame',
            name='last_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
