# Generated by Django 5.1.3 on 2024-12-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macrame', '0003_macrame_bidder_macrame_is_public_macrame_last_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrame',
            name='knot_description',
        ),
    ]
