# Generated by Django 5.1.3 on 2024-12-11 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrame', '0004_remove_macrame_knot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrame',
            name='bid_due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
