# Generated by Django 5.1.1 on 2024-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpainting',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='macrame',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
