# Generated by Django 5.1.1 on 2024-10-12 15:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_artpainting_image_macrame_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpainting',
            name='image',
            field=models.ImageField(upload_to='', verbose_name=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
        ),
        migrations.AlterField(
            model_name='macrame',
            name='image',
            field=models.ImageField(upload_to='', verbose_name=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
        ),
    ]
