# Generated by Django 5.1.3 on 2024-11-10 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technique_name', models.CharField(choices=[('Oil Painting', 'Oil Painting'), ('Acrilic Painting', 'Acrilic Painting'), ('Watercolor Painting', 'Watercolor Painting'), ('Gouache Painting', 'Gouache Painting'), ('Spray Painting', 'Spray Painting'), ('Mixed Media', 'Mixed Media'), ('Other', 'Other')], default='Other', max_length=20)),
                ('technique_description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
