# Generated by Django 5.1.3 on 2024-11-24 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_painting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artpainting',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artpainting',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_paintings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artpainting',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
