# Generated by Django 5.1.3 on 2024-12-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_painting', '0003_remove_artpainting_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpainting',
            name='bidder',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artpainting',
            name='last_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
