# Generated by Django 5.1.3 on 2024-12-09 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_painting', '0004_artpainting_bidder_artpainting_last_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpainting',
            name='bid_due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 14, 49, 0, 28438, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
