# Generated by Django 5.1.3 on 2024-11-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_artoniauser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artoniauser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artoniauser',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
