# Generated by Django 5.1.2 on 2024-10-20 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Ensure this value contains only letters, numbers, and underscore', regex='^[A-Za-z0-9_]*$')]),
        ),
    ]
