# Generated by Django 5.1.2 on 2024-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop Music', 'POP'), ('Jazz Music', 'JAZZ'), ('R&B Music', 'R&B'), ('Rock Music', 'ROCK'), ('Country Music', 'COUNTRY'), ('Dance Music', 'DANCE'), ('Hip Hop Music', 'HIPHOP'), ('Other', 'OTHER')], default='Other', max_length=30),
        ),
    ]
